// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-AH9G92Sf871YzrlQlsw5MFE_XfGK6E',
    appId: '1:615104074259:web:2659f150d70c43849f65e6',
    messagingSenderId: '615104074259',
    projectId: 'uygulamam-181f6',
    authDomain: 'uygulamam-181f6.firebaseapp.com',
    databaseURL: 'https://uygulamam-181f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uygulamam-181f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5fh34rUXSOf5P4qcU-SmgACECVokRwWQ',
    appId: '1:615104074259:android:c187cfc7862a87739f65e6',
    messagingSenderId: '615104074259',
    projectId: 'uygulamam-181f6',
    databaseURL: 'https://uygulamam-181f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uygulamam-181f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTtRRsUZez_Q_Hyya4haqpJFAhqBuhrg',
    appId: '1:615104074259:ios:656a46330820f5839f65e6',
    messagingSenderId: '615104074259',
    projectId: 'uygulamam-181f6',
    databaseURL: 'https://uygulamam-181f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uygulamam-181f6.appspot.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-AH9G92Sf871YzrlQlsw5MFE_XfGK6E',
    appId: '1:615104074259:web:699ea5ae61d48e159f65e6',
    messagingSenderId: '615104074259',
    projectId: 'uygulamam-181f6',
    authDomain: 'uygulamam-181f6.firebaseapp.com',
    databaseURL: 'https://uygulamam-181f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uygulamam-181f6.appspot.com',
  );
}
